import { DesignTokens } from "./types";

export const TOKEN_PRESETS: DesignTokens[] = [
  {
    id: "minimal-dark",
    name: "Minimal Dark",
    primaryColor: "#111111",
    secondaryColor: "#1a1a1a",
    accentColor: "#ffffff",
    backgroundColor: "#0a0a0a",
    surfaceColor: "#141414",
    textColor: "#ffffff",
    textMuted: "#888888",
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    borderRadius: "soft",
    spacing: "spacious",
  },
  {
    id: "clean-light",
    name: "Clean Light",
    primaryColor: "#1a1a1a",
    secondaryColor: "#f5f5f5",
    accentColor: "#2563eb",
    backgroundColor: "#ffffff",
    surfaceColor: "#f8f8f8",
    textColor: "#111111",
    textMuted: "#666666",
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    borderRadius: "soft",
    spacing: "balanced",
  },
  {
    id: "warm-earth",
    name: "Warm Earth",
    primaryColor: "#2d2418",
    secondaryColor: "#f5efe6",
    accentColor: "#c47d3c",
    backgroundColor: "#faf6f0",
    surfaceColor: "#f0ebe3",
    textColor: "#2d2418",
    textMuted: "#8a7d6b",
    fontHeading: "'Georgia', serif",
    fontBody: "'Inter', sans-serif",
    borderRadius: "rounded",
    spacing: "spacious",
  },
  {
    id: "bold-modern",
    name: "Bold Modern",
    primaryColor: "#000000",
    secondaryColor: "#f0f0f0",
    accentColor: "#ff4d00",
    backgroundColor: "#ffffff",
    surfaceColor: "#f5f5f5",
    textColor: "#000000",
    textMuted: "#555555",
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    borderRadius: "sharp",
    spacing: "compact",
  },
  {
    id: "soft-premium",
    name: "Soft Premium",
    primaryColor: "#1e1e2e",
    secondaryColor: "#e8e4f0",
    accentColor: "#7c5cbf",
    backgroundColor: "#f8f7fc",
    surfaceColor: "#eeeaf5",
    textColor: "#1e1e2e",
    textMuted: "#6b6580",
    fontHeading: "'Georgia', serif",
    fontBody: "'Inter', sans-serif",
    borderRadius: "rounded",
    spacing: "spacious",
  },
];

export function getTokenCSS(tokens: DesignTokens): React.CSSProperties {
  const radiusMap = { sharp: "0px", soft: "8px", rounded: "16px" };
  const spacingMap = { compact: "1", balanced: "1.25", spacious: "1.5" };

  return {
    "--bs-primary": tokens.primaryColor,
    "--bs-secondary": tokens.secondaryColor,
    "--bs-accent": tokens.accentColor,
    "--bs-bg": tokens.backgroundColor,
    "--bs-surface": tokens.surfaceColor,
    "--bs-text": tokens.textColor,
    "--bs-text-muted": tokens.textMuted,
    "--bs-font-heading": tokens.fontHeading,
    "--bs-font-body": tokens.fontBody,
    "--bs-radius": radiusMap[tokens.borderRadius],
    "--bs-spacing-factor": spacingMap[tokens.spacing],
  } as React.CSSProperties;
}
